version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasksdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    build:
      context: .
      dockerfile: src/BlazorWasm.Server/Dockerfile
    environment:
      ConnectionStrings__Default: Server=mysql;Database=tasksdb;User=root;Password=root;
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5001:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
